// Generated by scripts/emit_types.py from schema/supernova.schema.json.
// Do not edit by hand -- change the schema and re-run the script.
//
// Supernova LMS Record Types

export interface Student {
  id: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  studentId: string;
  currentGradeLevel: GradeLevel;
  enrollmentStatus: "active" | "inactive" | "transferred";
  enrollmentDate: string;
  schoolId: string;
  districtId: string;
  metadata?: Metadata;
}

export type GradeLevel = "K" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12";

export type Subject = "Math" | "ELA" | "Science" | "Social Studies" | "Arts" | "Physical Education" | "all";

export interface Metadata {
  dataSource?: string;
  isApproximate?: boolean;
  qualityFlags?: string[];
  confidentialityLevel?: "public" | "internal" | "restricted";
  lastSyncDate?: string;
}

export interface Standard {
  id: string;
  framework: string;
  subject: Subject;
  gradeLevel: GradeLevel;
  /// The single course at this grade that covers this standard.
  course?: string;
  standardCode: string;
  standardText: string;
  domainOrCluster: string;
  cluster?: string;
  /// CCSS (+) standards, beyond the college-ready threshold.
  advanced?: boolean;
  /// NCAS and SHAPE use levels rather than grades.
  proficiencyLevel?: string;
  metadata?: Record<string, unknown>;
}

export interface MasteryRecord {
  id: string;
  standardId: string;
  subject: Subject;
  schoolYear: SchoolYear;
  curriculumUnitId?: string;
  sectionId?: string;
  status: "mastered" | "not_mastered" | "in_progress";
  /// Derived from evidenceCount: 0 none, 1-2 insubstantial, 3-5 moderate, 6+
  /// substantial.
  evidenceStrength: "none" | "insubstantial" | "moderate" | "substantial";
  evidenceCount: number;
  firstEvidenceDate?: string | null;
  mostRecentEvidenceDate?: string | null;
  evidence?: string[];
  isReDemonstration?: boolean;
  metadata?: Metadata;
}

export interface Evidence {
  id: string;
  masteryRecordId: string;
  studentId: string;
  standardId: string;
  dataSourceType: "assessment" | "assignment" | "observation" | "studentArtifact" | "quiz" | "performanceTask" | "project" | "discussion" | "other";
  dataSourceId?: string;
  dataSourceName: string;
  title: string;
  evidenceDate: string;
  studentArtifactLink?: string;
  analysis: {
    demonstratesStandard: boolean;
    contextNotes: string;
  };
  metadata?: Record<string, unknown>;
}

export type SchoolYear = string;

export interface AttendanceRecord {
  id: string;
  studentId: string;
  schoolYear: SchoolYear;
  /// Only non-present days are stored. Present days are recoverable from the
  /// school calendar minus these exceptions.
  attendanceModel: "exceptions_only";
  attendanceExceptions: ({
    date: string;
    status: "absent" | "excused_absent" | "tardy" | "excused_tardy" | "partial_day";
    notes?: string | null;
  })[];
  metrics: {
    daysEnrolled: number;
    daysPresent: number;
    daysAbsent: number;
    daysExcusedAbsent?: number;
    tardyCount?: number;
    attendanceRate: number;
    chronicAbsenteeismFlag: boolean;
  };
  metadata?: Metadata;
}

export interface BehaviorRecord {
  id: string;
  studentId: string;
  schoolYear: SchoolYear;
  incidents: ({
    id: string;
    date: string;
    incidentType: "discipline_referral" | "office_visit" | "detention" | "suspension" | "expulsion" | "positive_recognition";
    severity?: "low" | "medium" | "high" | null;
    description: string;
    staff?: string;
    location?: string;
    /// Set when incidents localize to one class.
    subject?: string | null;
    outcome?: string;
  })[];
  metrics: Record<string, unknown>;
  metadata?: Metadata;
}

export interface HealthRecord {
  id: string;
  studentId: string;
  schoolYear: SchoolYear;
  healthEvents: Record<string, unknown>[];
  flags: {
    chronicHealthCondition?: boolean;
    mentalHealthConcern?: boolean;
    foodInsecurityRisk?: boolean;
    housingInstability?: boolean;
    otherWellnessFactors?: unknown[];
  };
  /// confidentialityLevel is always restricted; viewing requires
  /// view_health_detail.
  metadata?: Metadata;
}

export interface Staff {
  id: string;
  firstName: string;
  lastName: string;
  staffId: string;
  role: "teacher" | "building_administrator" | "district_administrator" | "counselor" | "nurse" | "special_education_teacher" | "support_staff";
  /// Null for district-level roles.
  schoolId?: string | null;
  districtId: string;
  subjectsTaught?: string[];
  gradeLevelsTaught?: GradeLevel[];
  email?: string;
  hireDate?: string;
  employmentStatus?: "active" | "inactive" | "former";
  metadata?: Metadata;
}

export interface Section {
  id: string;
  schoolId: string;
  schoolYear: SchoolYear;
  name: string;
  gradeLevel: GradeLevel;
  /// 'all' for self-contained elementary sections.
  subject: Subject;
  teacherId: string;
  coTeacherIds?: string[];
  period?: string | null;
  roomNumber?: string;
  instructionalModel: "self_contained" | "departmentalized";
  roster: string[];
  enrollmentCount?: number;
  metadata?: Metadata;
}

export interface CurriculumUnit {
  id: string;
  sectionId: string;
  schoolYear: SchoolYear;
  subject: Subject;
  name: string;
  sequence: number;
  markingPeriodId?: string;
  startDate: string;
  endDate: string;
  plannedInstructionalDays?: number;
  standardIds: string[];
  /// Days whose absence carries more weight than a review day. This is what
  /// turns absence counts into absence impact.
  keyInstructionDates?: {
    date: string;
    description: string;
    standardIds?: string[];
  }[];
  pacing: {
    percentContentCovered: number;
    percentTimeElapsed: number;
    pacingStatus: "ahead" | "on_track" | "slightly_behind" | "behind";
  };
  status: "not_started" | "in_progress" | "completed";
  metadata?: Metadata;
}

export interface InterruptionRecord {
  id: string;
  sectionId: string;
  schoolYear: SchoolYear;
  interruptions: ({
    id: string;
    date: string;
    interruptionType: "assembly" | "fire_drill" | "lockdown_drill" | "schedule_change" | "early_dismissal" | "pull_out" | "testing_window" | "technology_failure" | "substitute_coverage" | "other";
    description?: string;
    minutesLost: number;
    wasPlanned: boolean;
    curriculumUnitId?: string | null;
    loggedBy?: string;
  })[];
  metrics: Record<string, unknown>;
  metadata?: Metadata;
}

export interface ParticipationRecord {
  id: string;
  studentId: string;
  sectionId: string;
  schoolYear: SchoolYear;
  /// A recent window only. Metrics are computed over every assignment; storing
  /// them all is a gradebook the dashboards never render.
  recentAssignments?: ({
    id: string;
    assignmentTitle: string;
    curriculumUnitId?: string;
    assignedDate: string;
    dueDate: string;
    submittedDate?: string | null;
    completionStatus: "completed_on_time" | "completed_late" | "incomplete" | "missing" | "excused";
    standardIds?: string[];
  })[];
  assignmentsRetained?: number;
  assignmentsTotal?: number;
  metrics: {
    assignmentsAssigned: number;
    assignmentsCompleted: number;
    completionRate: number;
    onTimeRate?: number;
    completionRateByMarkingPeriod?: {
      markingPeriod?: number;
      completionRate?: number;
    }[];
  };
  metadata?: Metadata;
}

export interface Guardian {
  id: string;
  firstName: string;
  lastName: string;
  relationship: "mother" | "father" | "stepparent" | "grandparent" | "foster_parent" | "legal_guardian" | "other";
  email?: string;
  phone?: string;
  preferredContactMethod?: "email" | "phone" | "text" | "mail";
  preferredLanguage?: string;
  studentLinks: ({
    studentId: string;
    custodyStatus: "primary" | "secondary" | "joint" | "none";
    /// Per-link, not per-guardian: custody arrangements are frequently
    /// asymmetric. This is the enforcement point for the parent dashboard.
    hasEducationalRights: boolean;
  })[];
  metadata?: Metadata;
}

/**
 * Carries identity and authorization only. No credential material appears
 * anywhere in this dataset.
 */
export interface User {
  id: string;
  username: string;
  email?: string;
  displayName: string;
  principalType: "staff" | "guardian" | "student" | "community_member";
  principalId?: string | null;
  roleAssignments: RoleAssignment[];
  accountStatus: "active" | "inactive" | "locked" | "pending";
  lastLoginDate?: string | null;
  metadata?: Record<string, unknown>;
}

/**
 * Authorization is a role PLUS a scope. Building and district administrators
 * share a role and differ only in scope.
 */
export interface RoleAssignment {
  id: string;
  userId: string;
  role: "teacher" | "building_administrator" | "district_administrator" | "school_board_member" | "guardian" | "student" | "community_member" | "counselor" | "nurse" | "special_education_teacher";
  scopeType: "section" | "school" | "district" | "student" | "public";
  /// An empty array is valid: a guardian without educational rights sees
  /// nothing, rather than being blocked.
  scopeIds: string[];
  permissions: ("view_aggregate_mastery" | "view_individual_students" | "view_student_names" | "view_attendance_detail" | "view_behavior_detail" | "view_health_detail" | "view_special_services_detail" | "view_evidence_artifacts" | "record_mastery" | "log_interruptions" | "add_intervention_notes")[];
  effectiveDate?: string;
  expirationDate?: string | null;
  metadata?: Record<string, unknown>;
}

export interface ResearchCitation {
  id: string;
  claim: string;
  topic: "attendance" | "behavior" | "engagement" | "mastery_progression" | "family_involvement" | "interruptions" | "special_services" | "prior_achievement";
  source: {
    authorOrOrganization: string;
    title: string;
    publicationYear: number;
    url: string;
    sourceType: "peer_reviewed" | "government_report" | "research_organization" | "meta_analysis" | "other";
  };
  applicableRoles?: string[];
  triggerConditions?: Record<string, unknown>;
  /// Required. A citation library that presented correlation as causation would
  /// undercut the project's research-grounded and accountable-not-punitive
  /// commitments.
  confidenceNote: string;
  metadata: {
    addedDate?: string;
  };
  /// What checking this claim found, and who signed off on it. A source check
  /// asks whether the cited document exists and says what the claim says; a
  /// sign-off asks whether the claim is fit to put in front of a stakeholder.
  /// Only the second produces "verified", and only a named person can give it.
  review: {
    /// Derived from sourceCheck and signOff rather than set by hand, so it
    /// cannot drift out of agreement with them. Nothing but "verified" should
    /// reach a stakeholder-facing view without its unverified marker, and only
    /// a signOff produces it.
    status: "unreviewed" | "source_checked" | "revision_required" | "verified" | "withdrawn";
    /// Null means nobody has read the source, which is not the same as the
    /// source being fine.
    sourceCheck: {
      checkedOn: string;
      /// Who or what did the checking. A review with no reviewer is the state
      /// this library was in for six phases.
      checkedBy: string;
      /// Does the URL reach the document the record names?
      sourceReachable: boolean;
      /// Are author, title, year and source type right?
      recordAccurate: boolean;
      /// Whether the source establishes what the claim sentence says, read
      /// alone. A stakeholder reads the claim without the confidenceNote under
      /// it.
      support: "supported" | "partial" | "unsupported";
      finding: string;
      defects: string[];
    } | null;
    /// A named person accepting this claim for stakeholder display, and
    /// accountable for it afterwards. Cannot be produced by a source check
    /// however thorough. Null on every claim in this library.
    signOff: {
      reviewer: string;
      /// Standing to make the judgement, recorded so a sign-off can be weighed
      /// rather than trusted.
      credentials: string;
      signedOn: string;
      outcome: "accepted" | "withdrawn";
      note?: string;
    } | null;
  };
}
