#!/usr/bin/env python3
"""Emit TypeScript interfaces from the JSON Schema the generator is validated against.

The schema in `schema/supernova.schema.json` is already the contract the dataset
is checked against by `scripts/validate.py`. Hand-writing a parallel set of
TypeScript types would create a second contract that drifts from the first the
moment a generator field changes. Deriving them means a schema change surfaces as
a type error in the app rather than as `undefined` at runtime.

Stdlib only, matching the generator. Run after any schema change:

    python3 scripts/emit_types.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "supernova.schema.json"
OUTPUT_PATH = REPO_ROOT / "app" / "src" / "types" / "supernova.ts"

SCALARS = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
    "null": "null",
}


def type_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def render(schema: dict, indent: int, nested: list[str]) -> str:
    """Render one schema node as a TypeScript type expression."""
    if "$ref" in schema:
        return type_name(schema["$ref"])

    if "const" in schema:
        return json.dumps(schema["const"])

    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    node_type = schema.get("type")

    # A nullable object -- `"type": ["object", "null"]` -- still has to render
    # its shape, so this has to come before the object branch below. Letting the
    # object branch win drops the `| null` silently, and the field where that
    # first mattered is a citation's sign-off, which is absent on every claim in
    # the library. A type saying otherwise would have the app dereferencing a
    # reviewer who does not exist.
    if isinstance(node_type, list) and "null" in node_type:
        rest = [entry for entry in node_type if entry != "null"]
        if not rest:
            return "null"
        inner = dict(schema)
        inner["type"] = rest[0] if len(rest) == 1 else rest
        return f"{render(inner, indent, nested)} | null"

    if node_type == "object" or "properties" in schema:
        # `allOf` in this schema carries if/then *constraints* (evidenceCount 0
        # implies evidenceStrength "none"), not additional shape. Those are rules
        # the generator and validator enforce; they say nothing about the type.
        return render_object(schema, indent, nested)

    if "allOf" in schema:
        parts = [
            render(part, indent, nested) for part in schema["allOf"] if "if" not in part
        ]
        return " & ".join(parts) if parts else "unknown"

    if isinstance(node_type, list):
        return " | ".join(SCALARS.get(entry, "unknown") for entry in node_type)

    if node_type == "array":
        items = schema.get("items")
        if not items:
            return "unknown[]"
        rendered = render(items, indent, nested)
        # `(A | B)[]` -- a bare union would bind only the last member to the array.
        needs_parens = " | " in rendered or " & " in rendered
        return f"({rendered})[]" if needs_parens else f"{rendered}[]"

    return SCALARS.get(node_type, "unknown")


def render_object(schema: dict, indent: int, nested: list[str]) -> str:
    properties = schema.get("properties", {})
    if not properties:
        return "Record<string, unknown>"

    required = set(schema.get("required", []))
    pad = "  " * (indent + 1)
    lines = ["{"]

    for name, definition in properties.items():
        description = definition.get("description")
        if description:
            for line in wrap(description, 76 - len(pad)):
                lines.append(f"{pad}/// {line}")
        # Anything not in `required` is genuinely optional in the output: the
        # generator omits fields at their default rather than writing nulls, so
        # the UI has to read defensively and the types should say so.
        optional = "" if name in required else "?"
        key = name if re.fullmatch(r"[A-Za-z_$][\w$]*", name) else json.dumps(name)
        lines.append(f"{pad}{key}{optional}: {render(definition, indent + 1, nested)};")

    lines.append("  " * indent + "}")
    return "\n".join(lines)


def wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        if current and len(" ".join(current + [word])) > width:
            lines.append(" ".join(current))
            current = [word]
        else:
            current.append(word)
    if current:
        lines.append(" ".join(current))
    return lines


def emit(schema: dict) -> str:
    defs = schema["$defs"]
    out = [
        "// Generated by scripts/emit_types.py from schema/supernova.schema.json.",
        "// Do not edit by hand -- change the schema and re-run the script.",
        "//",
        f"// {schema.get('title', 'Supernova')}",
        "",
    ]

    for name, definition in defs.items():
        description = definition.get("description")
        if description:
            out.append("/**")
            for line in wrap(description, 76):
                out.append(f" * {line}")
            out.append(" */")

        nested: list[str] = []
        body = render(definition, 0, nested)

        if body.startswith("{"):
            out.append(f"export interface {name} {body}")
        else:
            out.append(f"export type {name} = {body};")
        out.append("")

    return "\n".join(out)


def main() -> int:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(emit(schema), encoding="utf-8")

    count = len(schema["$defs"])
    relative = OUTPUT_PATH.relative_to(REPO_ROOT)
    print(f"  wrote {count} types to {relative}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
