#!/usr/bin/env python3
"""Validate the Supernova synthetic dataset and write the validation report.

    python3 scripts/validate.py

Regenerates in memory and checks both tiers: structural integrity, and the
narrative coherence the dashboards actually depend on. Writes
`data/validation-report.md` and exits non-zero if anything failed.
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from generator.aggregates import build_aggregates
from generator.config import CURRENT_SCHOOL_YEAR, MASTER_SEED
from generator.emit import DATA_DIR
from generator.pipeline import AS_OF_DATE, generate
from generator.standards_catalog import load_catalog, validate_catalog
from generator.validate import (
    Report,
    validate_aggregates,
    validate_narrative,
    validate_structure,
)


def write_report(report: Report, dataset, path: Path) -> None:
    lines: list[str] = []
    add = lines.append

    add("# Supernova Dataset Validation Report")
    add("")
    add(
        "Generated by `scripts/validate.py`. This report is the artifact "
        "demonstrating the dataset is *narratively coherent*, not merely "
        "well-formed. Structural checks confirm the data is valid; the narrative "
        "checks confirm it tells a believable story."
    )
    add("")
    add(f"- **Master seed:** `{MASTER_SEED}`")
    add(f"- **Current school year:** {CURRENT_SCHOOL_YEAR}")
    add(f"- **Viewing date:** {AS_OF_DATE.isoformat()}")
    add(f"- **Status:** {'PASSED' if report.passed else 'FAILED'}")
    add("")

    add("## Dataset Contents")
    add("")
    add("| Record type | Count |")
    add("|---|---:|")
    for key, value in dataset.counts.items():
        label = "".join(f" {c.lower()}" if c.isupper() else c for c in key).strip()
        add(f"| {label.capitalize()} | {value:,} |")
    add("")

    if report.errors:
        add("## Failures")
        add("")
        for message in report.errors:
            add(f"- **{message}**")
        add("")

    if report.warnings:
        add("## Warnings")
        add("")
        for message in report.warnings:
            add(f"- {message}")
        add("")

    add("## Checks")
    add("")
    add("| Check | Result |")
    add("|---|---|")
    for label, value in report.findings:
        add(f"| {label} | {value} |")
    add("")

    add("## What These Checks Mean")
    add("")
    add(
        "**Absence-to-mastery correlation** is the flagship measure. If mastery "
        "were generated independently of attendance, gaps would spread evenly "
        "across every unit and this number would sit near zero. A clear positive "
        "value means gaps actually land in the units a student missed, which is "
        "what makes the correlation narratives in the UI design possible."
    )
    add("")
    add(
        "**Behavioral localization** proves the system isolates correlation rather "
        "than assuming a struggling student struggles everywhere. The dip should "
        "appear in the affected subject and not across the board."
    )
    add("")
    add(
        "**Tier fidelity** is measured on completed units only. The unit currently "
        "in progress legitimately has thin evidence for every student in February, "
        "which would otherwise blur the distinction between tiers."
    )
    add("")
    add(
        "**Transfer honesty** confirms the generator records missing history as a "
        "data quality flag rather than inventing a past to fill the gap."
    )
    add("")
    add("---")
    add("")
    add(
        "*Every student, guardian, and staff member in this dataset is synthetic. "
        "No real student record, name, or artifact appears anywhere.*"
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    print("Supernova dataset validation")
    print()

    catalog = load_catalog()
    catalog_problems = validate_catalog(catalog)

    report = Report()
    for problem in catalog_problems:
        report.error(f"Standards catalog: {problem}")
    if not catalog_problems:
        report.finding("Standards catalog", f"{len(catalog)} standards, no problems")

    print("  generating dataset...", flush=True)
    dataset = generate()

    print("  structural checks...", flush=True)
    validate_structure(dataset, report)

    print("  aggregate reconciliation...", flush=True)
    aggregates = build_aggregates(dataset)
    validate_aggregates(dataset, aggregates, report)

    print("  narrative coherence...", flush=True)
    validate_narrative(dataset, report)

    report_path = DATA_DIR / "validation-report.md"
    write_report(report, dataset, report_path)

    print()
    for label, value in report.findings:
        print(f"    {label:52} {value}")

    if report.warnings:
        print()
        for message in report.warnings:
            print(f"    WARNING  {message}")

    print()
    if report.errors:
        print(f"  FAILED with {len(report.errors)} error(s):")
        for message in report.errors:
            print(f"    - {message}")
        print()
        print(f"  report written to {report_path}")
        return 1

    print("  PASSED")
    print(f"  report written to {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
